version: '3'
services:
  web: 
    build: 
      context: ./web
      dockerfile: ./Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - ./web:/app
  mysql:
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    ports:
    - "3306:3306"
    volumes:
    - ./mysql:/data
    

